### PR TITLE
HW for class 8,11,12 and 13 - all assignments now submitted

### PR DESCRIPTION
**Pull request by AAmbia**
Hi Martin, 
I have now completed submitting my assignments. I realize the commits I made yesterday also included my assignments and reconstructed files. 

Thanks.
Aron

### CODE REVIEW

**Comment by mobjohnson** [comment]
the pull request you sent yesterday showed you having closed it. please ass
a new file in one of your student folders and add and commit it, then do
the pull request.

Thanks!

*Martin Johnson*
Full-Stack Web Developer
mobjohnson.com

**Comment by mobjohnson** [comment]
*add a new file*

*Martin Johnson*
Full-Stack Web Developer
mobjohnson.com

**Comment by AAmbia** [comment]
Ok. Will do. Thanks.

**Comment by AAmbia** [comment]
Done. 
Aron

**Pull request closed without merging**
